# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: leeroya.com
email: leeroya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leeroya.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leeroyashworth
github_username:  leeroya
google_analytics_tracking_id: UA-45570731-1
# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-material-theme
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  - jekyll-spaceship
# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Gitlab

github: https://github.com/leeroya
#github: https://github.com/jameshamann/jekyll-material-theme
medium: https://www.linkedin.com/in/lee-roy-ashworth-179946b7

skills:
  - name: angularjs
  - name: csharp
  - name: javascript
  - name: dot-net
  - name: typescript
  - name: git
  - name: kubernetes
    uri: /assets/images/kubernetes-icon-color.png
  - name: ssh
  - name: docker

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
