image: docker:latest
services:
  - docker:dind

pages:
  stage: deploy
  script:
  - mkdir .public
  - docker run --rm --volume="$PWD:/srv/jekyll" jekyll/jekyll:3.8.5 jekyll build
  - cp -r ./_site/* .public
  # - cp -r ./.well-known/* .public/.well-known
  - mkdir .public/.well-known
  - mkdir .public/.well-known/acme-challenge
  - touch .public/.well-known/acme-challenge/t15HR-ceYToBfdtwXkDn0XJYSwHO30eJuuU1Lx2fx40.html
  - echo 't15HR-ceYToBfdtwXkDn0XJYSwHO30eJuuU1Lx2fx40.ZN1yLCTYc4FCkfzwKlCtM-Lkg9KQND3aqZyapnmjL6U' > .public/.well-known/acme-challenge/t15HR-ceYToBfdtwXkDn0XJYSwHO30eJuuU1Lx2fx40.html
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
